FROM python:3.9

WORKDIR /app

RUN pip install --upgrade pip

COPY requirements.txt .

COPY .env .

RUN pip install -r requirements.txt --no-cache-dir

COPY . .

CMD ["gunicorn", "--bind", "0.0.0.0:8000", "kittygram_backend.wsgi"]